'shopify_purchase': {'auth': ('20627b91731e8d8ee338bf786ae29feb',
  '045febd59c1d2acc3d00ac309360ea46'),
 'db_field_map': {'browser_ip': 'browser_ip',
  'created_at': 'created_at',
  'customer_id': 'customer.id',
  'is_paid': 'financial_status',
  'landing_site': 'landing_site',
  'price': 'total_price',
  'purchase_id': 'id',
  'referring_site': 'referring_site',
  'user_agent': 'client_details.user_agent'},
 'db_model': server.app.common.models.Purchase,
 'db_session': <flask_sqlalchemy.SignallingSession at 0x115c92588>,
 'endpoint': 'https://@xspeed.myshopify.com/admin/orders.json',
 'headers': {'Content-Type': 'application/json'},
 'json_data_keys': 'orders',
 'params': 'None',
 'primary_keys': ['purchase_id']},

'shopify_customer': {'auth': ('20627b91731e8d8ee338bf786ae29feb',
                       '045febd59c1d2acc3d00ac309360ea46'),
                      'db_field_map': {'created_at': 'created_at',
                       'customer_id': 'id',
                       'email_address': 'email',
                       'fname': 'first_name',
                       'lname': 'last_name',
                       'marketing_allowed': 'accepts_marketing',
                       'purchase_count': 'orders_count',
                       'total_spent_so_far': 'total_spent'},
                      'db_model': server.app.common.models.Customer,
                      'db_session': <flask_sqlalchemy.SignallingSession at 0x11638be80>,
                      'endpoint': 'https://@xspeed.myshopify.com/admin/customers.json',
                      'headers': {'Content-Type': 'application/json'},
                      'json_data_keys': 'customers',
                      'params': 'None',
                      'primary_keys': ['customer_id']},

'magento_purchase': {'db_field_map': {'created_at': 'created_at',
                      'customer_id': 'customer_id',
                      'price': 'total_invoiced',
                      'purchase_id': 'quote_id'},
                     'db_model': server.app.common.models.Purchase,
                     'db_session': <flask_sqlalchemy.SignallingSession at 0x1165537b8>,
                     'endpoint': 'http://127.0.0.1:32768/index.php/rest/V1/orders?searchCriteria',
                     'headers': {'Authorization': 'Bearer npk3nc7gyhn8leab9baifl5075q45uhl',
                      'Content-Type': 'application/json'},
                     'json_data_keys': 'items',
                     'params': 'None',
                     'primary_keys': ['purchase_id']},

'bigcommerce_purchase': {'auth': ('test', '07d63370ed9ddb2eee9143acb91b18af38cb5b9d'),
                         'db_field_map': {'browser_ip': 'ip_address',
                          'created_at': 'date_created',
                          'customer_id': 'customer_id',
                          'is_paid': 'payment_status',
                          'price': 'total_ex_tax',
                          'purchase_id': 'id'},
                         'db_model': server.app.common.models.Purchase,
                         'db_session': <flask_sqlalchemy.SignallingSession at 0x10ab16a90>,
                         'endpoint': 'https://store-vd63texh7u.mybigcommerce.com/api/v2/orders.json',
                         'headers': {'Content-Type': 'application/json'},
                         'json_data_keys': None,
                         'params': None,
                         'primary_keys': ['purchase_id']},
'x2crm_customer':{'db_field_map': {'city': 'city',
                   'created_at': 'createDate',
                   'customer_id': 'id',
                   'email_address': 'email',
                   'fname': 'firstName',
                   'interest_area': 'interest',
                   'lname': 'lastName'},
                  'db_model': server.app.common.models.Customer,
                  'db_session': <flask_sqlalchemy.SignallingSession at 0x10ab0add8>,
                  'endpoint': 'http://demo.x2crm.com/index.php/api2/Contacts/',
                  'headers': {'Authorization': 'Basic YWRtaW46dGVzdA==',
                   'Content-Type': 'application/json'},
                  'json_data_keys': None,
                  'params': None,
                  'primary_keys': ['customer_id']},
'stripe_customer': {'auth': ('sk_test_C9SgTuKd9DN2PT6hFLPMzlts', ''),
                    'db_field_map': {'created_at': 'created',
                     'customer_id': 'id',
                     'email_address': 'email'},
                    'db_model': server.app.common.models.Customer,
                    'db_session': <flask_sqlalchemy.SignallingSession at 0x10ab99080>,
                    'endpoint': 'https://api.stripe.com/v1/customers',
                    'headers': {'Content-Type': 'application/json'},
                    'json_data_keys': 'data',
                    'params': None,
                    'primary_keys': ['customer_id']}

