joint-js:
    contents:
        - bower_components/lodash/lodash.js
        - bower_components/backbone/backbone.js
        - bower_components/jointjs/dist/joint.js
    
joint-css:
    contents:
        - bower_components/jointjs/dist/joint.css

directed-graph-js:
    contents:
        - bower_components/graphlib/dist/graphlib.core.js
        - bower_components/dagre/dist/dagre.core.js
        - bower_components/jointjs/dist/joint.layout.DirectedGraph.js
        - contents:
            - app/common/js/journeyGrapher.js
            - app/common/js/jointRichElement.js
          filters: babeljs, rjsmin
          output: gen/journey_elements.%(version)s.js

bootstrap-js:
    contents:
        - bower_components/jquery/jquery.js
        - bower_components/bootstrap/dist/js/bootstrap.js

bootstrap-css:
    contents:
        - bower_components/bootstrap/dist/css/bootstrap.min.css

graphing-js:
    contents:
        - app/common/js/graphing/d3.v4.min.js
        - app/common/js/graphing/d3-scale-chromatic.v1.min.js
        - app/common/js/graphing/maps/topojson.v2.min.js
        - bower_components/d3/d3.js
        - bower_components/c3/c3.js
        - contents:
          - app/common/js/graphing/pieChartEmlStats.js
          - app/common/js/graphing/emlSendGrapher.js
          - app/common/js/graphing/dataGrapher.js
          - app/common/js/graphing/day_hour.js
          - app/common/js/graphing/map_graph.js
          filters: babeljs
          output: gen/graphing.babel.js

graphing-css:
    contents:
      - bower_components/c3/c3.css

data-manager-js:
    contents:
        - bower_components/moment/moment.js
        - app/common/js/dataManager.js
        - bower_components/bootstrap-table/dist/bootstrap-table.js
data-manager-css:
    contents:
        - bower_components/bootstrap-table/dist/bootstrap-table.css

query-builder-js:
    contents:
        - bower_components/moment/moment.js
        - bower_components/jQuery-QueryBuilder/dist/js/query-builder.standalone.min.js
        - app/common/js/dataBuilderUtils.js
        - app/common/js/dataBuilder.js
        - bower_components/bootstrap-table/dist/bootstrap-table.js
        - bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js

query-builder-css:
    contents:
        - bower_components/jQuery-QueryBuilder/dist/css/query-builder.default.min.css
        - bower_components/bootstrap-table/dist/bootstrap-table.css
        - bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css
        - app/common/css/query_builder.css

task-admin-css:
    contents:
        - bower_components/bootstrap-table/dist/bootstrap-table.css

task-admin-js:
    contents:
        - bower_components/moment/moment.js
        - app/common/js/taskBuilder.js
        - bower_components/bootstrap-table/dist/bootstrap-table.js

base-css:
    contents:
        - bootstrap-css
        - app/common/css/base.css
    filters: cssmin
    output: gen/base.%(version)s.css

base-js:
    contents:
        - bootstrap-js
        - bower_components/knockout/dist/knockout.js
        - app/common/js/polling.js
    filters: rjsmin
    output: gen/base.%(version)s.js

journey-view-css:
    contents:
        - joint-css
        - graphing-css
        - app/stats/css/journey_view.css
    filters: cssmin
    output: gen/journey_view.%(version)s.css

journey-view-js:
    contents:
        - joint-js
        - directed-graph-js
        - graphing-js
        - contents:
            - app/stats/js/journey_view.js
          filters: babeljs
          output: gen/journey_view.babel.js
    filters: rjsmin
    output: gen/journey_view.%(version)s.js

report-view-css:
    contents:
        - graphing-css
        - app/stats/css/report_view.css
    filters: cssmin
    output: gen/report_view.%(version)s.css

report-view-js:
    contents:
        - graphing-js
        - contents:
            - app/stats/js/report_view.js
          filters: babeljs
          output: gen/report_view.babel.js
    filters: rjsmin
    output: gen/report_view.%(version)s.js

devpage-joint-js:
    contents:
        - bootstrap-js
        - joint-js
        - graphing-js
        - query-builder-js
        - app/stats/js/devpage_joint.js
    filters: rjsmin
    output: gen/devpage_joint.%(version)s.js

devpage-joint-css:
    contents:
        - joint-css
        - graphing-css
        - bootstrap-css
        - query-builder-css
        #        - app/stats/css/devpage_joint.css
    filters: cssmin
    output: gen/devpage_joint.%(version)s.css

map-graph-js:
    contents:
        - app/common/js/graphing/d3.v4.min.js
        - app/common/js/graphing/d3-scale-chromatic.v1.min.js
        - app/common/js/graphing/maps/topojson.v2.min.js
        - app/stats/js/graphing/map_graph.js
    filters: rjsmin
    output: gen/map_graph.%(version)s.js

map-graph-css:
    contents:
        - app/stats/css/map_graph.css
    filters: cssmin
    output: gen/map_graph.%(version)s.css

mosaico-editor-js:
    contents:
        - mosaico/dist/vendor/jquery-ui.min.js
        - mosaico/dist/vendor/jquery.ui.touch-punch.min.js
        - mosaico/dist/vendor/load-image.all.min.js
        - mosaico/dist/vendor/canvas-to-blob.min.js
        - mosaico/dist/vendor/knockout-jqueryui.min.js
        - mosaico/dist/vendor/evol.colorpicker.min.js
        - mosaico/dist/vendor/tinymce.min.js
        - mosaico/dist/mosaico.min.js
        - contents:
            - mosaico/dist/vendor/jquery.iframe-transport.js
            - mosaico/dist/vendor/jquery.fileupload.js
            - mosaico/dist/vendor/jquery.fileupload-process.js
            - mosaico/dist/vendor/jquery.fileupload-image.js
            - mosaico/dist/vendor/jquery.fileupload-validate.js
          filters: rjsmin
          output: gen/mosaico-deps.min.js
    filters: rjsmin
    output: gen/editor.%(version)s.js

mosaico-editor-css:
    contents:
        - mosaico/dist/vendor/evol.colorpicker.min.css
        - mosaico/dist/mosaico-material.min.css
        - mosaico/dist/vendor/notoregular/stylesheet.css
    output: gen/editor.%(version)s.css

mosaico-index-css:
    contents:
        - mosaico/dist/mosaico-material.min.css
        - mosaico/dist/vendor/notoregular/stylesheet.css
    filters: cssmin
    output: gen/index.%(version)s.css

