"""empty message

Revision ID: d059ddfd663e
Revises: 
Create Date: 2017-08-23 19:10:20.433529

"""

# revision identifiers, used by Alembic.
revision = 'd059ddfd663e'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist')
    op.add_column('report', sa.Column('aggregate_field_2', sa.String(length=255), nullable=True))
    op.add_column('report', sa.Column('aggregate_op_2', sa.String(length=255), nullable=True))
    op.add_column('report', sa.Column('math_op', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'math_op')
    op.drop_column('report', 'aggregate_op_2')
    op.drop_column('report', 'aggregate_field_2')
    op.create_table('artist',
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('popularity', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('uri', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('href', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('_last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_last_ext_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='artist_pkey')
    )
    ### end Alembic commands ###


def upgrade_Galileo():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist')
    op.add_column('report', sa.Column('aggregate_field_2', sa.String(length=255), nullable=True))
    op.add_column('report', sa.Column('aggregate_op_2', sa.String(length=255), nullable=True))
    op.add_column('report', sa.Column('math_op', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade_Galileo():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'math_op')
    op.drop_column('report', 'aggregate_op_2')
    op.drop_column('report', 'aggregate_field_2')
    op.create_table('artist',
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('popularity', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('uri', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('href', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('_last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_last_ext_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='artist_pkey')
    )
    ### end Alembic commands ###


def upgrade_test_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist')
    op.add_column('report', sa.Column('aggregate_field_2', sa.String(length=255), nullable=True))
    op.add_column('report', sa.Column('aggregate_op_2', sa.String(length=255), nullable=True))
    op.add_column('report', sa.Column('math_op', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade_test_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'math_op')
    op.drop_column('report', 'aggregate_op_2')
    op.drop_column('report', 'aggregate_field_2')
    op.create_table('artist',
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('popularity', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('uri', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('href', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('_last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_last_ext_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='artist_pkey')
    )
    ### end Alembic commands ###


def upgrade_test7():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist')
    op.add_column('report', sa.Column('aggregate_field_2', sa.String(length=255), nullable=True))
    op.add_column('report', sa.Column('aggregate_op_2', sa.String(length=255), nullable=True))
    op.add_column('report', sa.Column('math_op', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade_test7():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'math_op')
    op.drop_column('report', 'aggregate_op_2')
    op.drop_column('report', 'aggregate_field_2')
    op.create_table('artist',
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('popularity', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('uri', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('href', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('_last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_last_ext_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='artist_pkey')
    )
    ### end Alembic commands ###

