{
    'magento': {
        'headers': {
                'Content-Type': 'application/json',
                'Authorization': 'Bearer '
        },
        'params': null,
        'customer': {
            'endpoint': '/index.php/rest/V1/customers/search?searchCriteria',
            'primary_keys': ['customer_id'],
            'json_data_keys': 'items',
            'db_field_map': {'customer_id': id',
                             'email_address':'email',
                             'fname':'firstname',
                             'lname':'lastname',
                             'created_at':'created_at',
                            }
        },
        'purchase': {
            'endpoint': '/index.php/rest/V1/orders?searchCriteria',
            'primary_keys': ['purchase_id'],
            'json_data_keys': 'items',
            'db_field_map': {'purchase_id':'quote_id',
                             'customer_id':'customer_id',
                             'created_at':'created_at',
                             'price':'total_invoiced',
                            }
        }
    },

    'zoho': {
        'headers': {
            'Content-Type': 'application/json',
            'Authorization': 'Zoho-authtoken '
        },
        'params': {'scope':'crmapi', 'fromIndex': 1, 'toIndex': 200, 'newFormat': 2, 'version': 2},
        'transform_response_data': True,
        'customer': {
            'endpoint': '/Contacts/getRecords',
            'primary_keys': ['customer_id'],
            'json_data_keys': 'response.result.Contacts.row',

            'db_field_map': {'customer_id':'CONTACTID',
                             'email_address':'Email',
                             'fname':'First Name',
                             'city':'Mailing City',
                             'lname':'Last Name',
                             'created_at':'Created Time',
                            }
        }
    },

    'x2crm': {
        'headers': {
            'Content-Type': 'application/json',
            'Authorization': 'Basic '
        },
        'params': null,
        'customer': {
            'endpoint': '/index.php/api2/Contacts/',
            'primary_keys': ['customer_id'],
            'json_data_keys': null,

            'db_field_map': {'customer_id':'id',
                             'email_address':'email',
                             'fname':'firstName',
                             'city':'city',
                             'interest_area':'interest',
                             'lname':'lastName',
                             'created_at':'createDate',
                            }
        }
    },

    'shopify': {
        'headers': {'Content-Type': 'application/json'},
        'params': null,
        'purchase': {
            'pagination': {
              'endpoint': '/admin/orders.json?limit=250=&page=',
              'count_endpoint': '/admin/orders/count.json',
              'count_data_key': 'count',
              'records_limit': 250,
            },
            'primary_keys': ['purchase_id'],
            'json_data_keys': 'orders',
            'db_field_map': {'purchase_id':'id',
                             'customer_id':'customer.id',
                             'created_at':'created_at',
                             'price':'total_price',
                             'is_paid':'financial_status',
                             'referring_site':'referring_site',
                             'landing_site':'landing_site',
                             'browser_ip':'browser_ip',
                             'user_agent':'client_details.user_agent'
                            }
        },
        'customer': {
            'pagination': {
              'endpoint': '/admin/customers.json?limit=250=&page=',
              'count_endpoint': '/admin/customers/count.json',
              'count_data_key': 'count',
              'records_limit': 250,
            },
            'primary_keys': ['customer_id'],
            'json_data_keys': 'customers',
            'db_field_map': {'customer_id':'id',
                             'email_address':'email',
                             'fname':'first_name',
                             'lname':'last_name',
                             'marketing_allowed':'accepts_marketing',
                             'created_at':'created_at',
                             'purchase_count':'orders_count',
                             'total_spent_so_far':'total_spent'
                            }
        }
    },
    'bigcommerce': {
        'headers': {'Content-Type': 'application/json'},
        'params': null,
        'purchase': {
            'endpoint': '/api/v2/orders.json',
            'primary_keys': ['purchase_id'],
            'json_data_keys': null,
            'db_field_map': {'purchase_id':'id',
                                 'customer_id':'customer_id',
                                 'created_at':'date_created',
                                 'price':'total_ex_tax',
                                 'is_paid':'payment_status',
                                 'browser_ip':'ip_address'
                            }
        },
        'customer': {
            'endpoint': '/api/v2/customers.json',
            'primary_keys': ['customer_id'],
            'json_data_keys': null,
            'db_field_map': {'customer_id':'id',
                             'email_address':'email',
                             'fname':'first_name',
                             'lname':'last_name',
                             'marketing_allowed':'accepts_marketing',
                             'created_at':'date_created'
                            }
        }
    },
    'stripe': {
        'headers': {'Content-Type': 'application/json'},
        'params': null,
        'customer': {
            'endpoint': '/customers',
            'primary_keys': ['customer_id'],
            'json_data_keys': 'data',
            'db_field_map': {'customer_id':'id',
                             'email_address':'email',
                             'created_at':'created'
                            }

        }
    },
    'mc_email_data':{
      'creds':
        {
            'filename': 'tracking_extract.zip',
            'filepath': '/Export/',
            'ftp_url': 'ftp.s7.exacttarget.com'
        },
      'file_map': {
            'journey_sends.csv': {
                'primary_keys': ['SubscriberKey', 'EventDate'],
                'db_field_map': {
                              'SendID': 'SendID',
                              'SubscriberKey': 'SubscriberKey',
                              'TriggeredSendExternalKey': 'TriggererSendDefinitionObjectID',
                              'EventDate': 'EventDate'
                },
                'ftp_path': '/Export/',
                'file_encoding': 'utf16'
            },
            'journey_opens.csv': {
                'primary_keys': ['SubscriberKey', 'EventDate'],
                'db_field_map': {
                              'SendID': 'SendID',
                              'SubscriberKey': 'SubscriberKey',
                              'TriggeredSendExternalKey': 'TriggererSendDefinitionObjectID',
                              'EventDate': 'EventDate'
                },
                'ftp_path': '/Export/',
                'file_encoding': 'utf16'
            },
            'journey_clicks.csv': {
                'primary_keys': ['SubscriberKey', 'EventDate'],
                'db_field_map': {
                              'SendID': 'SendID',
                              'SubscriberKey': 'SubscriberKey',
                              'TriggeredSendExternalKey': 'TriggererSendDefinitionObjectID',
                              'EventDate': 'EventDate'
                },
                'ftp_path': '/Export/',
                'file_encoding': 'utf16'
            },
            'SendJobs.csv': {
               'primary_keys': ['SendID'],
               'db_field_map':{
                   'SendID': 'SendID',
                   'SendDefinitionExternalKey': 'SendDefinitionExternalKey',
                   'EmailName': 'EmailName',
                   'SchedTime': 'SchedTime',
                   'SentTime': 'SentTime',
                   'Subject': 'Subject',
                   'PreviewURL': 'PreviewURL'
               }
            },
            'Sent.csv':{
               'primary_keys':['SubscriberKey', 'EventDate'],
               'db_field_map':{
                   'SendID': 'SendID',
                   'SubscriberKey': 'SubscriberKey',
                   'EmailAddress': 'EmailAddress',
                   'EventDate': 'EventDate'
               }
            },
            'Opens.csv':{
               'primary_keys':['SubscriberKey', 'EventDate'],
               'db_field_map':{
                   'SendID': 'SendID',
                   'SubscriberKey': 'SubscriberKey',
                   'EmailAddress': 'EmailAddress',
                   'EventDate': 'EventDate',
                   'IsUnique': 'IsUnique',
                   'IpAddress': 'IpAddress',
                   'Country': 'Country',
                   'Region': 'Region',
                   'City': 'City',
                   'Latitude': 'Latitude',
                   'Longitude': 'Longitude',
                   'MetroCode': 'MetroCode',
                   'AreaCode': 'AreaCode',
                   'Browser': 'Browser',
                   'EmailClient': 'EmailClient',
                   'OperatingSystem': 'OperatingSystem',
                   'Device': 'Device'
               }
            },
            'Clicks.csv':{
               'primary_keys':['SubscriberKey', 'EventDate'],
               'db_field_map':{
                   'SendID': 'SendID',
                   'SubscriberKey': 'SubscriberKey',
                   'EmailAddress': 'EmailAddress',
                   'EventDate': 'EventDate',
                   'SendURLID': 'SendURLID',
                   'URLID': 'URLID',
                   'URL': 'URL',
                   'Alias': 'Alias',
                   'IsUnique': 'IsUnique',
                   'IpAddress': 'IpAddress',
                   'Country': 'Country',
                   'Region': 'Region',
                   'City': 'City',
                   'Latitude': 'Latitude',
                   'Longitude': 'Longitude',
                   'MetroCode': 'MetroCode',
                   'AreaCode': 'AreaCode',
                   'Browser': 'Browser',
                   'EmailClient': 'EmailClient',
                   'OperatingSystem': 'OperatingSystem',
                   'Device': 'Device'
               }
            }
      }
    },
    'mc_journeys': {
      'creds':
        {
            'auth_url': 'https://auth.exacttargetapis.com/v1/requestToken?legacy=1'
        }
    }
}
